import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

declare global {
  interface Window {
    Datamap: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js" strategy="beforeInteractive" />
        <Script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js" strategy="beforeInteractive" />
        <Script src="/datamaps.world.hires.min.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
